set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[7]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[6]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[5]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[4]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[3]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[2]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[1]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {r_out_reg_reg[0]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[7]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[6]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[5]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[4]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[3]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[2]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[1]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {g_out_reg_reg[0]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[7]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[6]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[5]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[4]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[3]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[2]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[1]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {active_pixel}]  -to [get_pins {b_out_reg_reg[0]/CE}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[0]}]  -to [get_pins {b_in_reg_reg[0]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[1]}]  -to [get_pins {b_in_reg_reg[1]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[2]}]  -to [get_pins {b_in_reg_reg[2]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[3]}]  -to [get_pins {b_in_reg_reg[3]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[4]}]  -to [get_pins {b_in_reg_reg[4]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[5]}]  -to [get_pins {b_in_reg_reg[5]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[6]}]  -to [get_pins {b_in_reg_reg[6]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[7]}]  -to [get_pins {b_in_reg_reg[7]/D}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[0]/C}]  -to [get_ports {b_out[0]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[1]/C}]  -to [get_ports {b_out[1]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[2]/C}]  -to [get_ports {b_out[2]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[3]/C}]  -to [get_ports {b_out[3]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[4]/C}]  -to [get_ports {b_out[4]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[5]/C}]  -to [get_ports {b_out[5]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[6]/C}]  -to [get_ports {b_out[6]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[7]/C}]  -to [get_ports {b_out[7]}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[0]}]  -to [get_pins {g_in_reg_reg[0]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[1]}]  -to [get_pins {g_in_reg_reg[1]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[2]}]  -to [get_pins {g_in_reg_reg[2]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[3]}]  -to [get_pins {g_in_reg_reg[3]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[4]}]  -to [get_pins {g_in_reg_reg[4]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[5]}]  -to [get_pins {g_in_reg_reg[5]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[6]}]  -to [get_pins {g_in_reg_reg[6]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[7]}]  -to [get_pins {g_in_reg_reg[7]/D}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[0]/C}]  -to [get_ports {g_out[0]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[1]/C}]  -to [get_ports {g_out[1]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[2]/C}]  -to [get_ports {g_out[2]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[3]/C}]  -to [get_ports {g_out[3]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[4]/C}]  -to [get_ports {g_out[4]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[5]/C}]  -to [get_ports {g_out[5]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[6]/C}]  -to [get_ports {g_out[6]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[7]/C}]  -to [get_ports {g_out[7]}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[0]}]  -to [get_pins {r_in_reg_reg[0]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[1]}]  -to [get_pins {r_in_reg_reg[1]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[2]}]  -to [get_pins {r_in_reg_reg[2]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[3]}]  -to [get_pins {r_in_reg_reg[3]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[4]}]  -to [get_pins {r_in_reg_reg[4]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[5]}]  -to [get_pins {r_in_reg_reg[5]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[6]}]  -to [get_pins {r_in_reg_reg[6]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[7]}]  -to [get_pins {r_in_reg_reg[7]/D}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[0]/C}]  -to [get_ports {r_out[0]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[1]/C}]  -to [get_ports {r_out[1]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[2]/C}]  -to [get_ports {r_out[2]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[3]/C}]  -to [get_ports {r_out[3]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[4]/C}]  -to [get_ports {r_out[4]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[5]/C}]  -to [get_ports {r_out[5]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[6]/C}]  -to [get_ports {r_out[6]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[7]/C}]  -to [get_ports {r_out[7]}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {r_out_reg_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {g_out_reg_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {b_out_reg_reg[0]/R}] -datapath_only 2.75
