# Created : 17:0:3, Wed Apr 6, 2013 : Sanjay Rai

ALL:
	cd PR_module_video_black_and_white/vivado_hd_flow_batch && vivado -mode batch -source vivado_batch.tcl 
	cd PR_module_video_bypass/vivado_hd_flow_batch && vivado -mode batch -source vivado_batch.tcl 
	cd PR_module_video_color_inv/vivado_hd_flow_batch && vivado -mode batch -source vivado_batch.tcl 
	cd PR_module_video_crossover/vivado_hd_flow_batch && vivado -mode batch -source vivado_batch.tcl 
	cd PR_module_video_softness/vivado_hd_flow_batch && vivado -mode batch -source vivado_batch.tcl 

clean:
	cd PR_module_video_black_and_white/vivado_hd_flow_batch && ./mk_clean.bat 
	cd PR_module_video_bypass/vivado_hd_flow_batch && ./mk_clean.bat 
	cd PR_module_video_color_inv/vivado_hd_flow_batch && ./mk_clean.bat 
	cd PR_module_video_crossover/vivado_hd_flow_batch && ./mk_clean.bat 
	cd PR_module_video_softness/vivado_hd_flow_batch && ./mk_clean.bat 
