set_max_delay -from [get_ports {b_in[0]}]  -to [get_pins {b_in_reg_reg[0]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[1]}]  -to [get_pins {b_in_reg_reg[1]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[2]}]  -to [get_pins {b_in_reg_reg[2]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[3]}]  -to [get_pins {b_in_reg_reg[3]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[4]}]  -to [get_pins {b_in_reg_reg[4]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[5]}]  -to [get_pins {b_in_reg_reg[5]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[6]}]  -to [get_pins {b_in_reg_reg[6]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {b_in[7]}]  -to [get_pins {b_in_reg_reg[7]/D}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[0]/C}]  -to [get_ports {b_out[0]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[1]/C}]  -to [get_ports {b_out[1]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[2]/C}]  -to [get_ports {b_out[2]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[3]/C}]  -to [get_ports {b_out[3]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[4]/C}]  -to [get_ports {b_out[4]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[5]/C}]  -to [get_ports {b_out[5]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[6]/C}]  -to [get_ports {b_out[6]}] -datapath_only 2.75
set_max_delay -from [get_pins {b_out_reg[7]/C}]  -to [get_ports {b_out[7]}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[0]}]  -to [get_pins {g_in_reg_reg[0]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[1]}]  -to [get_pins {g_in_reg_reg[1]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[2]}]  -to [get_pins {g_in_reg_reg[2]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[3]}]  -to [get_pins {g_in_reg_reg[3]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[4]}]  -to [get_pins {g_in_reg_reg[4]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[5]}]  -to [get_pins {g_in_reg_reg[5]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[6]}]  -to [get_pins {g_in_reg_reg[6]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {g_in[7]}]  -to [get_pins {g_in_reg_reg[7]/D}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[0]/C}]  -to [get_ports {g_out[0]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[1]/C}]  -to [get_ports {g_out[1]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[2]/C}]  -to [get_ports {g_out[2]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[3]/C}]  -to [get_ports {g_out[3]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[4]/C}]  -to [get_ports {g_out[4]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[5]/C}]  -to [get_ports {g_out[5]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[6]/C}]  -to [get_ports {g_out[6]}] -datapath_only 2.75
set_max_delay -from [get_pins {g_out_reg[7]/C}]  -to [get_ports {g_out[7]}] -datapath_only 2.75
set_max_delay -from [get_ports {hsync_in}]  -to [get_pins {hsync_in_reg_reg/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[0]}]  -to [get_pins {r_in_reg_reg[0]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[1]}]  -to [get_pins {r_in_reg_reg[1]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[2]}]  -to [get_pins {r_in_reg_reg[2]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[3]}]  -to [get_pins {r_in_reg_reg[3]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[4]}]  -to [get_pins {r_in_reg_reg[4]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[5]}]  -to [get_pins {r_in_reg_reg[5]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[6]}]  -to [get_pins {r_in_reg_reg[6]/D}] -datapath_only 2.75
set_max_delay -from [get_ports {r_in[7]}]  -to [get_pins {r_in_reg_reg[7]/D}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[0]/C}]  -to [get_ports {r_out[0]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[1]/C}]  -to [get_ports {r_out[1]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[2]/C}]  -to [get_ports {r_out[2]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[3]/C}]  -to [get_ports {r_out[3]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[4]/C}]  -to [get_ports {r_out[4]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[5]/C}]  -to [get_ports {r_out[5]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[6]/C}]  -to [get_ports {r_out[6]}] -datapath_only 2.75
set_max_delay -from [get_pins {r_out_reg[7]/C}]  -to [get_ports {r_out[7]}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/scaled_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_9/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_8/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_7/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_6/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_5/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_4/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_3/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_2/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_13/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_12/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_11/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_10/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_1/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r_0/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg_r/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/pipe_mov_ave_reg[15][0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[8]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/i_acc_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/data_in_reg_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[9]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[8]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[12]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[11]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[10]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_r/acc_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/scaled_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/pipe_mov_ave_reg[15][0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[8]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/i_acc_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/data_in_reg_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[9]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[8]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[12]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[11]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[10]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_g/acc_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/scaled_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/pipe_mov_ave_reg[15][0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[8]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/i_acc_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/data_in_reg_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[9]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[8]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[7]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[6]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[5]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[4]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[3]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[2]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[1]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[12]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[11]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[10]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {reset}]  -to [get_pins {U_moving_ave_b/acc_out_reg[0]/R}] -datapath_only 2.75
set_max_delay -from [get_ports {vsync_in}]  -to [get_pins {vsync_in_reg_reg/D}] -datapath_only 2.75
