# Created : 17:0:3, Wed Apr 6, 2013 : Sanjay Rai

ALL:
	cd PR_modules && make 
	cd vivado_hd_flow_batch && vivado -mode batch -source vivado_batch.tcl 

clean:
	cd PR_modules && make clean 
	cd vivado_hd_flow_batch && ./mk_clean.bat 
