rm -rf .Xil/
rm -rf .ngc2edfcache/
rm -rf FMC_DVIDP_CONFIG_test_drc_methodology_checks.rpt
rm -rf FMC_DVIDP_CONFIG_test_drc_timing_checks.rpt
rm -rf FMC_DVIDP_CONFIG_test.bit
rm -rf FMC_DVIDP_CONFIG_test.timing_rpt
rm -rf FMC_DVIDP_CONFIG_test.timing_summary_rpt
rm -rf planAhead.ngc2edif.log
rm -rf vivado.jou
rm -rf vivado.log
